project:
  type: website
  output-dir: docs

website:
  title: "Mara Alexeev's Website"
  draft-mode: gone # unlinked # Or 'gone' or 'visible'
  navbar:
    left:
      - posts.qmd # add your posts.qmd file to your navbar!
      - about.qmd
      - href: https://maraalexeev.github.io/cv/
        text: CV
  comments: 
    giscus:
      repo: MaraAlexeev/personal_website_v2
      repo-id: R_kgDOJFwsOQ
      category: General
      category-id: DIC_kwDOJFwsOc4CUrDd
      mapping: title #pathname was very gross format
      reactions-enabled: TRUE
      input-position: bottom
      theme: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



